// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.appobjects;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>O_XXX02</b><br>
 * Generated     : <b>2014/03/06 5:04:20 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  March 06, 2014
 * @author Administrator
 */
public abstract class O_XXX02Helper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * 大连论坛大连天健网大连交友房产汽车大学音乐足球电视台电影旅游生活: with default state.
	 *		.title : 大连论坛－大连天健网 大连|交友|房产|汽车|大学|音乐|足球|电视台|电影|旅游|生活
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://bbs.runsky.com/index.htm
	 */
	protected DocumentTestObject frame_main() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("frame_main"));
	}
	/**
	 * 大连论坛大连天健网大连交友房产汽车大学音乐足球电视台电影旅游生活: with specific test context and state.
	 *		.title : 大连论坛－大连天健网 大连|交友|房产|汽车|大学|音乐|足球|电视台|电影|旅游|生活
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://bbs.runsky.com/index.htm
	 */
	protected DocumentTestObject frame_main(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("frame_main"), anchor, flags);
	}
	
	/**
	 * node_999999918: with default state.
	 *		.id : node_999999918
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject frame_menu() 
	{
		return new GuiTestObject(
                        getMappedTestObject("frame_menu"));
	}
	/**
	 * node_999999918: with specific test context and state.
	 *		.id : node_999999918
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject frame_menu(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("frame_menu"), anchor, flags);
	}
	
	/**
	 * header_content: with default state.
	 *		.id : header_content
	 * 		.title : 
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_header_content() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_header_content"));
	}
	/**
	 * header_content: with specific test context and state.
	 *		.id : header_content
	 * 		.title : 
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_header_content(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_header_content"), anchor, flags);
	}
	
	/**
	 * ibody: with default state.
	 *		.id : ibody
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_ibody() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_ibody"));
	}
	/**
	 * ibody: with specific test context and state.
	 *		.id : ibody
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_ibody(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_ibody"), anchor, flags);
	}
	
	/**
	 * node_0: with default state.
	 *		.id : node_0
	 * 		.title : 
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_node_0() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_node_0"));
	}
	/**
	 * node_0: with specific test context and state.
	 *		.id : node_0
	 * 		.title : 
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_node_0(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_node_0"), anchor, flags);
	}
	
	/**
	 * ls_fastloginfield_ctrl: with default state.
	 *		.text : 用户名
	 * 		.href : javascript:;
	 * 		.id : ls_fastloginfield_ctrl
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_ls_fastloginfield_ctrl() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_ls_fastloginfield_ctrl"));
	}
	/**
	 * ls_fastloginfield_ctrl: with specific test context and state.
	 *		.text : 用户名
	 * 		.href : javascript:;
	 * 		.id : ls_fastloginfield_ctrl
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_ls_fastloginfield_ctrl(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_ls_fastloginfield_ctrl"), anchor, flags);
	}
	
	/**
	 * 天健慈善: with default state.
	 *		.text : 天健慈善
	 * 		.id : 
	 * 		.href : http://bbs.runsky.com/forum-1507-1.html
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_天健慈善() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_天健慈善"));
	}
	/**
	 * 天健慈善: with specific test context and state.
	 *		.text : 天健慈善
	 * 		.id : 
	 * 		.href : http://bbs.runsky.com/forum-1507-1.html
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_天健慈善(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_天健慈善"), anchor, flags);
	}
	
	/**
	 * HtmlOBJECT: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.OBJECT
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject object_htmlOBJECT() 
	{
		return new GuiTestObject(
                        getMappedTestObject("object_htmlOBJECT"));
	}
	/**
	 * HtmlOBJECT: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.OBJECT
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject object_htmlOBJECT(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("object_htmlOBJECT"), anchor, flags);
	}
	
	

	protected O_XXX02Helper()
	{
		setScriptName("appobjects.O_XXX02");
	}
	
}

