// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.appobjects;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>O_XXX01</b><br>
 * Generated     : <b>2014/03/17 11:04:30 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  March 17, 2014
 * @author Administrator
 */
public abstract class O_XXX01Helper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * 百度一下submit: with default state.
	 *		.id : su1
	 * 		.type : submit
	 * 		.value : 百度一下
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_search_submit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_search_submit"));
	}
	/**
	 * 百度一下submit: with specific test context and state.
	 *		.id : su1
	 * 		.type : submit
	 * 		.value : 百度一下
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_search_submit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_search_submit"), anchor, flags);
	}
	
	/**
	 * wd: with default state.
	 *		.id : kw1
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : wd
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_wd() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_wd"));
	}
	/**
	 * wd: with specific test context and state.
	 *		.id : kw1
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : wd
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_wd(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_wd"), anchor, flags);
	}
	
	/**
	 * wd: with default state.
	 *		.id : kw
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : wd
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_wd2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_wd2"));
	}
	/**
	 * wd: with specific test context and state.
	 *		.id : kw
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : wd
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_wd2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_wd2"), anchor, flags);
	}
	
	

	protected O_XXX01Helper()
	{
		setScriptName("appobjects.O_XXX01");
	}
	
}

